apiVersion: devopstoolkitseries.com/v1alpha1
kind: AppClaim
metadata:
  name: crossplane-deeps-demo
spec:
  id: crossplane-deeps-demo
  compositionSelector:
    matchLabels:
      type: backend
      location: local
  parameters:
    namespace: git-repos
    image: ttl.sh/crossplane-deeps-demo:0.0.3
    port: 8080
    host: my-repo.deeps.hsh
